export enum Arrow{
    DROITE="DROITE",
    GAUCHE="GAUCHE",
    HAUT="HAUT",
    BAS="BAS",
    DEUX_BAS="DEUX_BAS",
    TROIS_BAS="TROIS_BAS",
    DIRECTION_GAUCHE="DIRECTION_GAUCHE",
    DIRECTION_DROITE="DIRECTION_DROITE",
}